### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by daviddias99** [daviddias99/mas-online-marketplace-feup-aiad#18]
# Code related

- [x] Batch mode argument for choosing number of runs
- [x] Quando um buyer termina apagar o nó e outgoing edges
- [x] On non-batch-mode choose shown graphics using GUI
- [x] Vagas de buyers
- [x] Verificar ficheiros com várias runs

## Optional
- [x] Add option for  keeping only the last X edges
- [x] Command line argument for (not) showing the network
- [ ] Vagas de sellers
- [ ] Price setting (new network)
- [x] Plot do preço médio de mercado (no início)
- [ ] Chamar ActionAtEnd dos vários plots/histo qd Ctrl - C
- [ ] Gráficos de barras <<-----

# Non-code-related
 

- [x] Experiment 1: Crime compensa?
Com base nos plots de scam ver os q fazem mais dinheiro (sellers)
Strats - todas SMART (buyer e seller)
Elasticidade - 20
Paciencia - 100
Sellers: 20 - com 25
4 vagas buyers: 10 a querer 5 - intervalo 10 sec
Scam Factor - 25, 50, 75, 90
- [x] Experiment 2:  Is Smart actually SMART? (Buyer)
Com base nos plots de bs ver as strats q gastam menos dinheiro (buyer)
Elasticidade - 20
Paciencia - 100
Strats - todas SMART (seller)
Buyer - SMART, RELTFT, ABSTFT
Sellers: 20 - com 25
Buyers: 42 a querer 5
Scam Factor - 0, 75

- [x] Experiment 3: Elasticidade é benéfico? Começa a fazer os teus alongamentos!
Com base nos plots de elasticity ver os q fazem mais dinheiro (sellers)
Scam Factor - 0
Paciencia - 100
Strats - todas SMART (buyer e seller)
Sellers: 18 - com 25
Buyers: 40 a querer 5
Elasticidade - 10, 20, 30

- [x] Experiment 4: Is Smart actually SMART? (Seller)
Com base nos plots de bs ver as strats q fazem mais dinheiro (sellers)
Elasticidade - 20
Paciencia - 100
Seller Price-Picking: Smart todas
Buyer - SMART
Seller Offer: SMART, RELTFT, ABSTFT
Scam Factor - 0
Sellers: 18 - com 25
Buyers: 40 a querer 5

- [x] Feedback do prof
- [ ] Report
